# Task captures self implicitly
ü¶ã

## Verhalten
Im Gegensatz zu den meisten Closures wird bei einem Task `self` implizit ‚Äûcaptured‚Äú. Hier wird zum Beispiel `self` implizit Captured, weil handle zur entsprechenden Klasse geh√∂rt. 

```swift
Task {
   handle(...)
}
```

## ¬†Problem

Das kann ein Problem sein, wenn man einen Task hat der potentiell Unbegrenzt¬†l√§uft (=\> Memory Leak weil self nie fregegeben werden kann):

```swift
Task {
	for await value in myAsyncSequence {
		handle(...)
	}
}
```


## L√∂sung
Aber man kann das Problem so beheben:


```swift
Task { [weak self] in
	for await value in myAsyncSequence {
		guard let self else {return}
		handle(...)
	}
}
```

## Falsche L√∂sung!

Achtung, hier w√ºrde das Problem nicht gel√∂st!


```swift
Task { [weak self] in
	guard let self else {return}
	for await value in myAsyncSequence {
		handle(...)
	}
}
```

## ¬†Zusammenfassung
- Wie kann man in einem Task auf `self` Zugreifen
- Was f√ºr ein Problem kann entstehen?
- Wie kann man das Problem l√∂sen?

#learning unit#